Repository mentores-digital/vindi-plugin, pull requests merged in 2020-06, with the labels that each got.

#52 Estilizações caixas de alerta
  .gitignore
  config.codekit3
  src/VindiWoocommerce.php
  src/assets/css/admin.css
  src/assets/css/admin.css.map
  src/assets/images/copiar.svg
  src/assets/images/icon-1.svg
  src/assets/images/icon-2.png
  src/assets/images/icon-2.svg
  src/assets/images/icon-3.svg
  src/assets/images/icon-4.svg
  src/assets/sass/admin.sass
  src/includes/FrontendFilesLoader.php
  src/templates/admin-settings.html.php
  src/templates/creditcard-checkout.html.php
  src/validators/Dependencies.php
  src/views/invalid-api-key.php
  src/views/missing-critical-dependency.php
  src/views/missing-dependency.php
  src/views/product-status.php
Labels: enhancement

#57 Correções na aplicação de juros
  src/includes/gateways/CreditPayment.php
  src/utils/InterestPriceHandler.php
  src/utils/PaymentProcessor.php
Labels: bug

#58 Outro bug na criação produto
  src/controllers/PlansController.php
  src/controllers/ProductController.php
Labels: bug

#64 Adição do changelog e do template de tradução
  docs/CHANGELOG.md
  src/VindiWoocommerce.php
  src/i18n/languages/vindi-woocommerce.pot
  src/includes/gateways/BankSlipPayment.php
  src/utils/FrontendFilesLoader.php
  src/utils/SubscriptionStatusHandler.php
Labels: documentation
